### ISSUE TITLE
[BUG] Units of secondary info items not respected

### ISSUE THREAD

**Issue by cguedel** [flixlix/power-flow-card-plus#493]
**Describe the bug**
When adding a secondary info that contains a non-power unit, in my case the total energy use of the device today, the unit is still display with `W`/`kW`.

Using card version `v0.2.0-beta` installed via HACS.

**To Reproduce**
1. Add secondary info with a non power item to Home section
2. Observe value gets added a `W` unit, which is wrong

The item in question is a utility meter helper which correctly shows a `Wh` unit (see second screenshot)

**Expected behavior**
Unit from the secondary item configuration should be used.

**Screenshots**

![image](https://github.com/flixlix/power-flow-card-plus/assets/818878/55dc93d4-4fce-4d8d-ad6b-495b99965d0e)
![image](https://github.com/flixlix/power-flow-card-plus/assets/818878/1702404e-2971-4afe-b3be-b18e80283201)

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

- [x] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by jaytonic** [comment]
I'm also interested in this feature, since it would allow to display either the power, either the (daily) energy of my solar installation :)

**Comment by flixlix** [comment]
should be fixed in 0.2.1, can you please check?

**Comment by cguedel** [comment]
Doesn't seem fixed on my side. The sensor has unit of `Wh` and still shows up as `W`, even when setting no unit at all.

**Comment by cguedel** [comment]
Do you need any additional info from me?
